version: '3.7'
services:
  cockroach:
    networks:
      - proxy
    image: cockroachdb/cockroach:latest
    command: start-single-node --http-port 26256 --insecure
    restart: unless-stopped
    volumes:
      - './data/cockroach:/cockroach/cockroach-data'
    ports:
      - "127.0.0.1:26257:26257" # Cockroach
      - "127.0.0.1:26256:26256" # WebUI
  redis:  
    networks:
      - proxy
    image: redis
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - './data/redis:/data'
    ports:
      - "127.0.0.1:6379:6379"
  stack:
    networks:
      - proxy
    image: thethingsnetwork/lorawan-stack:3.6.0
    entrypoint: ttn-lw-stack
    command: start
    restart: unless-stopped
    depends_on:
      - redis
      - cockroach
    volumes:
      - './acme:/var/lib/acme'
      - './data/blob:/srv/ttn-lorawan/public/blob'
    environment:
      - TTN_LW_LOG_LEVEL=debug
      - TTN_LW_IS_DATABASE_URI=postgres://root@cockroach:26257/ttn_lorawan?sslmode=disable
      - TTN_LW_REDIS_ADDRESS=redis:6379
      # Let's Encrypt for "thethings.example.com":
      - TTN_LW_TLS_SOURCE=acme
      - TTN_LW_TLS_ACME_DIR=/var/lib/acme
      - TTN_LW_TLS_ACME_EMAIL=mail@example.org
      - TTN_LW_TLS_ACME_HOSTS=example.org
      - TTN_LW_TLS_ACME_DEFAULT_HOST=example.org
      # HTTP Server configuration:
      - TTN_LW_HTTP_COOKIE_HASH_KEY= # generate 64 bytes (openssl rand -hex 64)
      - TTN_LW_HTTP_COOKIE_BLOCK_KEY= # generate 32 bytes (openssl rand -hex 32)
      - TTN_LW_HTTP_METRICS_PASSWORD= # choose a password
      - TTN_LW_HTTP_PPROF_PASSWORD= # choose a password
      # Email configuration for "thethings.example.com":
      - TTN_LW_IS_EMAIL_SENDER_NAME="The Things Stack"
      - TTN_LW_IS_EMAIL_SENDER_ADDRESS=mail@example.org
      - TTN_LW_IS_EMAIL_NETWORK_CONSOLE_URL=https://example.org/console
      - TTN_LW_IS_EMAIL_NETWORK_IDENTITY_SERVER_URL=https://example.org/oauth
      # Web UI configuration for "thethings.example.com":
      - TTN_LW_IS_OAUTH_UI_CANONICAL_URL=https://example.org/oauth
      - TTN_LW_IS_OAUTH_UI_IS_BASE_URL=https://example.org/api/v3
      - TTN_LW_CONSOLE_OAUTH_AUTHORIZE_URL=https://example.org/oauth/authorize
      - TTN_LW_CONSOLE_OAUTH_TOKEN_URL=https://example.org/oauth/token
      - TTN_LW_CONSOLE_UI_CANONICAL_URL=https://example.org/console
      - TTN_LW_CONSOLE_UI_IS_BASE_URL=https://example.org/api/v3
      - TTN_LW_CONSOLE_UI_GS_BASE_URL=https://example.org/api/v3
      - TTN_LW_CONSOLE_UI_NS_BASE_URL=https://example.org/api/v3
      - TTN_LW_CONSOLE_UI_AS_BASE_URL=https://example.org/api/v3
      - TTN_LW_CONSOLE_UI_JS_BASE_URL=https://example.org/api/v3
      - TTN_LW_CONSOLE_UI_EDTC_BASE_URL=https://example.org/api/v3
      - TTN_LW_CONSOLE_UI_QRG_BASE_URL=https://example.org/api/v3
      # Console OAuth client and secret:
      - TTN_LW_CONSOLE_OAUTH_CLIENT_ID=console
      - TTN_LW_CONSOLE_OAUTH_CLIENT_SECRET= # generate a good one (openssl rand -hex 32)   
    labels:
      - traefik.enable=true
      - traefik.http.routers.ttn.rule=Host(`example.org`)
      - traefik.http.routers.ttn.entrypoints=websecure
      - traefik.http.routers.ttn.tls=true
      - traefik.http.routers.ttn.tls.certresolver=http
      - traefik.http.routers.ttn.middlewares=security-headers
      - traefik.http.routers.ttn.tls.options=default
      - traefik.http.services.ttn.loadbalancer.server.port=1885
networks:
   proxy:
    external: true
