version: '3.3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    networks:
      - traefik
    command:
      - --configFile=/static.yaml
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 1700:1700/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./letsencrypt:/letsencrypt 
      - ./traefik/traefik.log:/traefik.log
      - ./traefik/access.log:/access.log
      - ./traefik/static.yaml:/static.yaml
      - ./traefik/dynamic.yaml:/etc/traefik/dynamic.yaml
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.security-headers.headers.stsSeconds=31536000
      - traefik.http.middlewares.security-headers.headers.stsPreload=true
      - traefik.http.middlewares.security-headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true

      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https,security-headers
      - traefik.http.routers.https-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.https-catchall.entrypoints=websecure
      - traefik.http.routers.https-catchall.middlewares=security-headers

      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=admin
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.middlewares.admin.basicauth.users=admin:$$apr1$$SAMaaHjX$$ZCo51QWKtqCOzrfaSZxwc1

networks:
   traefik:
    external: true