---
version: '3.6'
services:
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    networks:
      - traefik
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.org'
    volumes:
      - 'gitlab-etc:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.rule=Host(`gitlab.example.org`)
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.tls=true
      - traefik.http.routers.gitlab.tls.certresolver=http
      - traefik.http.routers.gitlab.middlewares=security-headers
      - traefik.http.routers.gitlab.tls.options=default
      - traefik.http.services.gitlab.loadbalancer.server.port=80

volumes:
  gitlab-etc:
  gitlab-logs:
  gitlab-data:

networks:
  traefik:
    external: true