services:
  app:
    image: prolle/remotely
    container_name: remotely
    restart: always
    volumes:
      - ./Remotely.db:/var/www/remotely/db/Remotely.db
      - ./appsettings.Production.json:/var/www/remotely/appsettings.Production.json
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.remotely.rule=Host(`remotely.example.org`)
      - traefik.http.routers.remotely.entrypoints=websecure
      - traefik.http.routers.remotely.tls=true
      - traefik.http.routers.remotely.tls.certresolver=http
      - traefik.http.routers.remotely.middlewares=security-headers
      - traefik.http.routers.remotely.tls.options=default
      - traefik.http.services.remotely.loadbalancer.server.port=5000"   
networks:
  proxy:
    external: true