---
version: '3'
services:
  remotely:
    container_name: remotely
    build: ./
    image: prolle/remotely
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./Remotely.db:/remotely/Remotely.db
      - ./appsettings.Production.json:/remotely/appsettings.Production.json
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.remotely.rule=Host(`remotely.example.org`)
      - traefik.http.routers.remotely.entrypoints=websecure
      - traefik.http.routers.remotely.tls=true
      - traefik.http.routers.remotely.tls.certresolver=http
      - traefik.http.routers.remotely.middlewares=security-headers
      - traefik.http.routers.remotely.tls.options=default
      - traefik.http.services.remotely.loadbalancer.server.port=5000
networks:
  proxy:
    external: true