version: '3'

services:
  app:
    image: ronivay/xen-orchestra
    restart: always
    volumes:
      - ./xo-server:/var/lib/xo-server
      - ./redis:/var/lib/redis
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xoa.entrypoints=http"
      - "traefik.http.routers.xoa.rule=Host(`xoa.example.org`)"
      - "traefik.http.middlewares.xoa-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.xoa.middlewares=xoa-https-redirect"
      - "traefik.http.routers.xoa-secure.entrypoints=https"
      - "traefik.http.routers.xoa-secure.rule=Host(`xoa.example.org`)"
      - "traefik.http.routers.xoa-secure.tls=true"
      - "traefik.http.routers.xoa-secure.tls.certresolver=http"
      - "traefik.http.routers.xoa-secure.service=xoa"
      - "traefik.http.services.xoa.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    container_name: xoa

networks:
  proxy:
    external: true