---
version: '3.3'

services:
  chirpstack-network-server:
    container_name: chirpstack-network
    image: chirpstack/chirpstack-network-server:3
    networks:
      - chirpstack
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server

  chirpstack-application-server:
    container_name: chirpstack-application-server
    image: chirpstack/chirpstack-application-server:3
    networks:
      - traefik
      - chirpstack
    ports:
      - '8080'
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    labels:
      - traefik.enable=true
      - traefik.http.routers.appserver.rule=Host(`chirpstack.example.org`)
      - traefik.http.routers.appserver.entrypoints=websecure
      - traefik.http.routers.appserver.tls=true
      - traefik.http.routers.appserver.tls.certresolver=http
      - traefik.http.routers.appserver.middlewares=security-headers
      - traefik.http.routers.appserver.tls.options=default
      - traefik.http.services.appserver.loadbalancer.server.port=8080

  chirpstack-gateway-bridge:
    container_name: chirpstack-bridge-server
    image: chirpstack/chirpstack-gateway-bridge:3
    networks:
      - traefik
      - chirpstack
    ports:
      - 1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    labels:
      - traefik.enable=true
      - traefik.udp.routers.semtech.entrypoints=semtech
      - traefik.udp.routers.semtech.service=semtech-udp
      - traefik.udp.services.semtech-udp.loadbalancer.server.port=1700

  chirpstack-geolocation-server:
    container_name: chirpstack-geolocation-server
    image: chirpstack/chirpstack-geolocation-server:3
    networks:
      - chirpstack
    volumes:
      - ./configuration/chirpstack-geolocation-server:/etc/chirpstack-geolocation-server

  postgresql:
    container_name: postgresql
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - chirpstack
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:5-alpine
    networks:
      - chirpstack
    volumes:
      - ./data/redis:/data

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    networks:
      - chirpstack
    ports:
      - '1883'

networks:
   traefik:
    external: true
   chirpstack:
    external: true