version: '3'
services:
  nodered:
    networks:
      - proxy
    restart: always
    build: ./nodered
    volumes:
      - './nodered/data:/data'
    container_name: nodered
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.rule=Host(`nodered.example.org`)"
      - "traefik.http.routers.nodered.entrypoints=websecure"
      - "traefik.http.routers.nodered.tls=true"
      - "traefik.http.routers.nodered.tls.certresolver=http"
      - "traefik.http.routers.nodered.middlewares=security-headers"
      - "traefik.http.routers.nodered.tls.options=default"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"

  influxdb:
    networks:
      - proxy
    restart: always
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=ming_default
    volumes:
      - './influxdb:/var/lib/influxdb'
    container_name: influxdb

  grafana:
    networks:
      - proxy
    restart: always
    image: grafana/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/data:/var/lib/grafana # chown 472 on this dir.
    depends_on:
      - influxdb
    container_name: grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.example.org`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=http"
      - "traefik.http.routers.grafana.middlewares=security-headers"
      - "traefik.http.routers.grafana.tls.options=default"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  mosquitto:
    networks:
     - proxy
    restart: always
    build: ./mosquitto
    container_name: mosquitto

networks:
   proxy:
    external: true