---
version: "2"
services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=http://gitea:3000
    restart: always
    networks:
        - traefik
        - gitea
    volumes:
      - 'gitea-data:/data'
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`gitea.example.org`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.tls.certresolver=http
      - traefik.http.routers.gitea.middlewares=security-headers
      - traefik.http.routers.gitea.tls.options=default
      - traefik.http.services.gitea.loadbalancer.server.port=3000
  

  drone-server:
    container_name: drone-server
    image: drone/drone:0.8
    restart: always
    depends_on:
        - gitea
    networks:
        - gitea
    volumes:
      - 'drone-data:/var/lib/drone'
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone-server:8000
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://gitea:3000
      - DRONE_SECRET=secret
      - DRONE_NETWORK=gitea

  drone-agent:
    container_name: drone-agent
    image: drone/agent:0.8
    command: agent
    restart: always
    depends_on:
      - drone-server
    networks:
      - traefik
      - gitea
    volumes:
      - "tcp://socket-proxy:2375"
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=secret

volumes:
  gitea-data:

networks:
  traefik:
    external: true